Part12 omniauth
tbilous/thinknetica pull request #12
Opened 2016-11-30 14:24 UTC by tbilous

Жду замечаний.
Спасибо.

2016-11-30 16:26 UTC, vkurennov requested changes

2016-11-30 16:26 UTC, vkurennov commented on app/controllers/users/omniauth_callbacks_controller.rb
> +    return unless @user && @user.persisted?
А что увидит пользователь в этом случае? Сдается мне, что ничего хорошего (а именно - 500 ошибку). Надо бы покрыть тестами этот кейс.

2016-11-30 16:26 UTC, vkurennov commented on app/models/user.rb
> +      name = if auth[:provider] == 'github'
Это можно тренарным оператором записать, будет лаконичнее

2016-11-30 18:58 UTC, tbilous commented on app/controllers/users/omniauth_callbacks_controller.rb
> +    return unless @user && @user.persisted?
Там вообще по большому счёту эта проверка не нужна. Пользователь создаётся раньше. В том месте она уже ничего не решает, единственное - если вруг по какой-то причине, что-то пошло не так - то не доводит до креша и прекращает выполнение.

2016-11-30 18:59 UTC, tbilous commented on app/models/user.rb
> +      name = if auth[:provider] == 'github'
Пробовал, но чёт меня рубокоп заругал,  плюнул и так оставил.

2016-12-01 07:53 UTC, vkurennov commented on app/controllers/users/omniauth_callbacks_controller.rb
> +    return unless @user && @user.persisted?
Может быть, но лучше все-таки оставить и рендерить сообщение об ошибке юзеру.

2016-12-01 07:53 UTC, vkurennov commented on app/models/user.rb
> +      name = if auth[:provider] == 'github'
ок

2016-12-01 08:51 UTC, vkurennov approved these changes

2016-12-01 08:58 UTC, merged