Part 17 jobs
tbilous/thinknetica pull request #17
Opened 2016-12-19 16:12 UTC by tbilous

Спасибо, Жду замечаний

2016-12-19 17:21 UTC, vkurennov requested changes

2016-12-19 17:21 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question.subscriptions.create!(user_id: @question.user_id) if @question.save
Не лучшая мысль выбрасывать исключение в контроллере из-за ошибок валидации.

2016-12-19 17:21 UTC, vkurennov commented on app/controllers/subscriptions_controller.rb
> +    respond_with(@subscription = @question.subscriptions.create!(user: current_user))
зачем `create!`? Его стоит использовать в моделях, в котнроллерах это приведет к 500-й ошибке.

2016-12-19 17:21 UTC, vkurennov commented on app/jobs/new_answer_notification_job.rb
> +      QuestionSubscriptionMailer.notification_email(user, answer).deliver_now
Даже в фоновых задачах используй deliver_later для отправки писем. Так у тебя один процесс будет заниматься перебором подписчиков, а другие - рассылать письма, т.е. будет распаралелливание задач.

2016-12-19 17:21 UTC, vkurennov commented on app/models/answer.rb
> +  after_create :notify_mailer
Коллбеки принято записывать после ассоциаций, валидаций и скоупов.

2016-12-19 17:21 UTC, vkurennov commented on app/models/answer.rb
> +  def notify_mailer
Коллбеки нужно помещать в приватные методы

2016-12-19 17:21 UTC, vkurennov commented on app/models/question.rb
> +    all.where(created_at:
зачем тут all? ты так нарушаешь главную фишку скоупов - они не будут склеиваться. И вообще-то, all вызывается после where. В общем, тебе тут нужен только where

2016-12-19 17:21 UTC, vkurennov commented on app/models/question.rb
> +  scope :daily_questions, lambda { |date|
Зачем тут дублирование?

2016-12-19 17:21 UTC, vkurennov commented on app/models/question.rb
> +  def subscribe_owner
В приватные методы

2016-12-19 17:21 UTC, vkurennov commented on app/workers/daily_mail_worker.rb
> +class DailyMailWorker
Перепиши с использованием ActiveJob.

2016-12-19 17:21 UTC, vkurennov commented on spec/jobs/new_answer_notification_job_spec.rb
> +      NewAnswerNotificationJob.perform_later
Тут ты не работу job проверил, а работу стандартного метода perform_later. Даже если у тебя задача ничего делать не будет, тест пройдет. И зачем такой тест? Нужно тестировать то, что происходит в результате вызова этой задачи.

2016-12-19 17:21 UTC, vkurennov commented on spec/workers/daily_mail_worker_spec.rb
> +      expect { DailyMailWorker.perform_async }.to change(DailyMailWorker.jobs, :size).by(1)
И опять ты тестируешь работу системного метода perform_async вместо работы самой задачи

2016-12-19 18:13 UTC, tbilous commented on app/controllers/subscriptions_controller.rb
> +    respond_with(@subscription = @question.subscriptions.create!(user: current_user))
Поправил

2016-12-19 18:13 UTC, tbilous commented on app/jobs/new_answer_notification_job.rb
> +      QuestionSubscriptionMailer.notification_email(user, answer).deliver_now
Поправил

2016-12-19 18:13 UTC, tbilous commented on app/models/answer.rb
> +  after_create :notify_mailer
Поправил

2016-12-19 18:13 UTC, tbilous commented on app/models/answer.rb
> +  def notify_mailer
Поправил

2016-12-19 18:13 UTC, tbilous commented on app/models/question.rb
> +    all.where(created_at:
Поправил

2016-12-19 18:13 UTC, tbilous commented on app/models/question.rb
> +  scope :daily_questions, lambda { |date|
Поправил

2016-12-19 18:13 UTC, tbilous commented on app/models/question.rb
> +  def subscribe_owner
Поправил

2016-12-19 18:50 UTC, tbilous commented on spec/workers/daily_mail_worker_spec.rb
> +      expect { DailyMailWorker.perform_async }.to change(DailyMailWorker.jobs, :size).by(1)
Поправил

2016-12-19 18:50 UTC, tbilous commented on spec/jobs/new_answer_notification_job_spec.rb
> +      NewAnswerNotificationJob.perform_later
Поправил

2016-12-19 18:50 UTC, tbilous commented on app/workers/daily_mail_worker.rb
> +class DailyMailWorker
Поправил

2016-12-19 18:54 UTC, tbilous commented on app/controllers/questions_controller.rb
> +    @question.subscriptions.create!(user_id: @question.user_id) if @question.save
Тут я не знаю, как это сделать изящней. Подписка должна происходить после сохранения вопроса в базу. Делать каллбек в модели - не хочу, считаю, это не должно происходить в модели question  Посоветуйте пожалуйста.
Спасибо.

2016-12-20 09:07 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question.subscriptions.create!(user_id: @question.user_id) if @question.save
А вот как раз сделать коллбек в модели и есть правильное решение. Так мы гарантируем, что каким бы образом мы не создали вопрос (например, через API), у нас будет автор подписан на обновления. В остальных случаях мы не уверены, что сохранен вопрос и будет дублирование для каждого возможного способа создания вопроса

2016-12-20 09:11 UTC, vkurennov requested changes

2016-12-20 09:11 UTC, vkurennov commented on app/jobs/new_answer_notification_job.rb
> +      QuestionSubscriptionMailer.notification_email(user, answer).deliver_now
А что-то в коде по-прежнему deliver_now

2016-12-20 09:11 UTC, vkurennov commented on spec/jobs/daily_mail_job_spec.rb
> +    expect(DailyMailer).to receive(:digest).with(user).and_call_original
Надо проверить на списке юзеров, чтобы убедиться, что каждый получает дайджест

2016-12-20 09:11 UTC, vkurennov commented on spec/jobs/new_answer_notification_job_spec.rb
> +    expect(QuestionSubscriptionMailer).to receive(:notification_email).with(user, answer).and_call_original
Тут также на списке юзеров надо проверить

2016-12-20 09:11 UTC, vkurennov commented on spec/models/answer_spec.rb
> +        .to change { ActiveJob::Base.queue_adapter.enqueued_jobs.count }.by(1)
Тоже бессмысленный тест. Что с того, что какая-то задача будет запланирована? Нам важно знать, какая именно задача.

2016-12-20 09:24 UTC, tbilous commented on app/controllers/questions_controller.rb
> +    @question.subscriptions.create!(user_id: @question.user_id) if @question.save
Не приближаемся ли мы тут к "God class"? Есть модель подписок, есть у нее контроллер что занимается подписками, есть контроллер модели вопросов и обращение на создание подписки с него. это обращение может вызыватся а  может не вызыватся и подписка не есть обязательная для модели вопросов функция.  В результате никакого "подземного стука" на коллбеках. - каждый занимается своим делом и не лезет в чужое

2016-12-20 09:53 UTC, tbilous commented on app/jobs/new_answer_notification_job.rb
> +      QuestionSubscriptionMailer.notification_email(user, answer).deliver_now
Да, что-то я тут наверное "в обе стороны" поправил

2016-12-20 15:37 UTC, vkurennov approved these changes
Принято с замечаниями

2016-12-20 15:37 UTC, vkurennov commented on app/models/question.rb
> +  after_create :subscribe_owner
Коллбеки принято записывать уже после скоупов

2016-12-20 15:37 UTC, vkurennov commented on spec/jobs/daily_mail_job_spec.rb
> +    expect(DailyMailer).to receive(:digest).with(user).and_call_original
Не исправлено

2016-12-20 15:37 UTC, vkurennov commented on spec/jobs/new_answer_notification_job_spec.rb
> +    expect(QuestionSubscriptionMailer).to receive(:notification_email).with(user, answer).and_call_original
Тут тоже надо на списке юзеров проверить

2016-12-20 20:27 UTC, tbilous commented on spec/models/answer_spec.rb
> +        .to change { ActiveJob::Base.queue_adapter.enqueued_jobs.count }.by(1)
так другой в рамках теста и нет...

2016-12-21 06:13 UTC, tbilous commented on spec/jobs/new_answer_notification_job_spec.rb
> +    expect(QuestionSubscriptionMailer).to receive(:notification_email).with(user, answer).and_call_original
Поправил

2016-12-21 06:16 UTC, tbilous commented on app/models/question.rb
> +  after_create :subscribe_owner
Поправил

2016-12-21 06:16 UTC, tbilous commented on spec/jobs/daily_mail_job_spec.rb
> +    expect(DailyMailer).to receive(:digest).with(user).and_call_original
Поправил

2016-12-21 06:30 UTC, tbilous commented on spec/models/answer_spec.rb
> +        .to change { ActiveJob::Base.queue_adapter.enqueued_jobs.count }.by(1)
Поправил

2016-12-21 09:25 UTC, merged