Part4 controllers
tbilous/thinknetica pull request #3
Opened 2016-10-14 17:00 UTC by tbilous

Add controllers and tests

2016-10-14 20:30 UTC, vkurennov requested changes
Исправь замечания

2016-10-14 20:30 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :load_answer, only: [:destroy, :edit]
Ставь пустую строку между блоком before_action и методами.

2016-10-14 20:30 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      redirect_to question_path(@question)
Можно писать короче и сразу же передвать флеш-сообщение: `redirect_to @question, success: 'Nice'`

2016-10-14 20:30 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.update_attributes(strong_params)
Используй метод update, а не update_attributes

2016-10-14 20:30 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      render 'new'
Принято название вида, если он в том же контроллере, указывать как символ: `render :new`

2016-10-14 20:30 UTC, vkurennov commented on app/helpers/answers_helper.rb
> +module AnswersHelper
Удаляй пустые файлы, незачем хранить хлам в репозитории

2016-10-14 20:30 UTC, vkurennov commented on config/routes.rb
> +  resources :answers, only: [:create, :destroy]
По условиям задания, ресурс answers должен быть [вложен](http://guides.rubyonrails.org/routing.html#nested-resources) в ресурс questions. Иначе, откуда возьмется question_id в параметрах запроса?

2016-10-14 20:30 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, question_id: question.id, answer: attr }.to change(Answer, :count).by(1)
Надо проверить, что ответ связывается с вопросом. Это можно сделать прямо в change через ассоциации вопроса.

2016-10-14 20:30 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it 'redirect_to question' do
Отделяй тесты друг от друга пустыми строками

2016-10-14 20:30 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'with invalid attr' do
Контексты также надо отделять путсыми строками, это как абзацы в тексте.

2016-10-14 20:30 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      let(:attr) do
Зачем тут do и end, когда это однострочник?

2016-10-14 20:30 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
describe также надо отделять пустыми строками

2016-10-14 20:30 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    let!(:answer) { create(:answer, question_id: question.id) }
не надо указывать question_id, связывай по объектам: `create(:answer, question: question)`

2016-10-14 20:30 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +RSpec.describe QuestionsController, type: :controller do
Разреди код пустыми строками между логическими частями и тестами, это легче читается

2016-10-14 20:30 UTC, vkurennov commented on spec/support/database_cleaner.rb
> +RSpec.configure do |config|
А зачем тебе DatabaseCleaner на данном этапе?

2016-10-15 06:39 UTC, tbilous commented on app/controllers/questions_controller.rb
> +      redirect_to question_path(@question)
Потому, что в последующем строка может стать длиннее, записана локаль и т.д. Может появится необходимость отключать стоку 
Исправил

2016-10-15 06:45 UTC, tbilous commented on spec/controllers/answers_controller_spec.rb
> +      let(:attr) do
Взял код с соседнего контроллера проще было сделать так, чем переделывать строку. Убрал

2016-10-15 06:47 UTC, tbilous commented on spec/support/database_cleaner.rb
> +RSpec.configure do |config|
Что-бы потом не искать почему тесты валятся. Если уже пошла фабрика а там и фейкер на подходе.

2016-10-15 06:58 UTC, tbilous commented on spec/controllers/answers_controller_spec.rb
> +    let!(:answer) { create(:answer, question_id: question.id) }
Учили так не делать.
Исправлю

2016-10-15 10:31 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      redirect_to question_path(@question)
ну когда появится, тогда и будешь менять

2016-10-15 10:33 UTC, vkurennov commented on spec/support/database_cleaner.rb
> +RSpec.configure do |config|
И как это влияет на очистку БД? Пока все в одном процессе, данные в базе фактически не создаются, DC нужен, когда будут тесты для ajax, т.к. в этом случае требуется реальное сохранение в базе. Но это потребуется в 6-7 уроке. Оставь, просто мне не очень нравится, когда применяют инструменты без понимания того, зачем они нужны.

2016-10-15 10:36 UTC, vkurennov approved these changes
Принято, но учти замечания

2016-10-15 10:36 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, question_id: question, answer: { body: nil } }.to_not change(question.answers, :count)
Здесь в change должен быть просто Answer, т.к. важно проверить, что не создан вообще никакой ответ, вне завсисмости от его связи с вопросом.

2016-10-15 10:36 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    it 'renders the index template' do
it'ы тоже отделяй друг от друга пустыми строками

2016-10-15 10:58 UTC, tbilous commented on spec/support/database_cleaner.rb
> +RSpec.configure do |config|
Не вопрос конечно.  Эт оскорее вопрос workflow. На этом этапе мне и mysql, к примеру - достаточен.  И Spring не особо ещё влияет на скорость прохождение тестов. А, бутсрап - вообще непонятно зачем :)
Убираю :)

2016-10-15 12:30 UTC, merged