Tdd 5 acteptance
tbilous/thinknetica pull request #4
Opened 2016-10-18 21:37 UTC by tbilous

В ожидании табуреток
Да знаю, что плохо :( Но нужны ваши советы.

2016-10-19 10:58 UTC, vkurennov requested changes
Исправь замечания

2016-10-19 10:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to_question
Зачем делать редирект? Просто убери этот экшн и все, раз форма ответа на странице вопроса

2016-10-19 10:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to question_path(@question)
Можно писать короче: `redirect_to @question` и в этой связи твой метод redirect_to_question теряет смысл, т.к. кол-во знаков то же самое.

2016-10-19 10:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def index
Убери экшн

2016-10-19 10:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @question = Answer.find(params[:id]).question
У тебя есть метод load_answer, который загружает ответ, зачем его исключать для edit и update, если в итоге получаем дублирование?
Ну и в задании ничего про edit и update не сказано, зачем усложнять себе работу?

2016-10-19 10:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@question)
Просто redirect_to @question

2016-10-19 10:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to root_path, alert: 'NO RIGHTS!' if current_user.id !=
А зачем искать вопрос? У нас же может только автор ответа удалить свой ответ. Ну и зачем снова делать find, когда есть метод load_answer?

И еще момент: проверка на авторство у нас будет встречаться еще не раз, поэтому стоит ее вынести в метод модели User, чтобы вызывать так: current_user.author_of?(@answer)

2016-10-19 10:58 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question = current_user && current_user.questions.new
1. Причем тут current_user? 
2. если нужна проверка, вынеси ее в постфиксный if, это легче читается

2016-10-19 10:58 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @answer = current_user && @question.answers.build
Также избавься от && в присваивании.

2016-10-19 10:58 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    redirect_to root_path, alert: 'NO RIGHTS!' if current_user != Question.find(params[:id]).user
Сравнивать надо по id, т.к. в противном случае, ты грузишь ассоциацию user из базы, чего делать не следует. Ну и вопрос уже загружен, зачем ты снова его из базы тянешь? 
И замени на вызов метода `User#author_of?`

2016-10-19 10:58 UTC, vkurennov commented on app/helpers/owner_helper.rb
> +  def owner?(object)
Вынеси это в модель User, и достаточно прсто сравнения user_id и id, не усложняй

2016-10-19 10:58 UTC, vkurennov commented on app/models/answer.rb
>    belongs_to :question
А связи с юезром у ответа нет?

2016-10-19 10:58 UTC, vkurennov commented on app/models/user.rb
> +  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
Devise умеет валидировать email, за это отвечает модуль validatable, который у тебя подключен

2016-10-19 10:58 UTC, vkurennov commented on app/views/questions/index.html.slim
> +        = link_to 'Reg', new_user_registration_path
Ссылки на регистрацию и вход надо в лейаут перенести, чтобы они на каждой странице были

2016-10-19 10:58 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - if owner?(@question)
Вызов `current_user.owner?(@question)` будет более правильным, т.к. это объектный подход, да и метод будет доступен не только в видах

2016-10-19 10:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    @question_author_user = create :user
Используй let для создания тестовых данных и вынести в хелпер логин, как показано в скринкасте

2016-10-19 10:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>        it 'save the new answer in a DB' do
Описание теста не совпадает с реализацией, должно быть "не сохраняет ответ в БД"

2016-10-19 10:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it 'delete from DB' do
НЕ удаляет из БД

2016-10-19 10:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'user is not owner' do
А для create этот контекст важен?

2016-10-19 10:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        context 'with valid attributes' do
Нужен тест на то, что созданный ответ связывается с залогиненным юзером

2016-10-19 10:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        let!(:answer) { create(:answer, question: question, user_id: @user.id) }
Контексты для автора/не автора лучше перенсти под конкретный экшн, т.е. внутрь нужного describe

2016-10-19 10:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        let!(:answer) { create(:answer, question: question, user_id: @user.id) }
Не надо связывать по user_id, просто `user: @user`

2016-10-19 10:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      describe 'POST create' do
Чем создание отличается в 2-х контекстах? Ничем, тогда зчаем его дублировать?
Еще раз: конектсы вынеси под конкретные describe и только там, где это имеет смысл.

2016-10-19 10:58 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>  RSpec.describe QuestionsController, type: :controller do
Те же замечания, что и к  AnswersController

2016-10-19 10:58 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +  scenario 'Root page have title' do
Отделяй let от  сценариев и сценарии друг от друга пустой строкой.

2016-10-19 10:58 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +    expect(page).to have_title 'Home page'
Этот тест абсолютно не имеет отношения к тестируемой фиче

2016-10-19 10:58 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +feature 'not authorized user cant to create question', %q{
Фича должна быть  "создание вопроса", вариант "незалогиненный юзер не может создать вопрос" - это сценарий, а не фича.

2016-10-19 10:58 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +feature 'not authorized user cant to create answer', %q{
Это должен быть сценарий в рамках фичи "пользователь может создать овтет".

2016-10-19 10:58 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +    expect(page).to_not have_link 'Delete answer'
Как наличие этой ссылки относится к созданию ответа?

2016-10-19 10:58 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +  User see form for question on root page
Что это за длиннющее описание?

2016-10-19 10:58 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +feature 'authorized have rights on create and edit question', %q{
Каждая фича должна быть в отдельном файле

2016-10-19 10:58 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +  scenario 'user see form on root page and can to create and to destroy the question' do
создание и удаление - это разные фичи, и  у них есть разные сценарии, не надо всем мешать в кучу.

2016-10-19 10:58 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +    click_link 'Delete question'
Это отдельная фича и сценарий

2016-10-19 10:58 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +    expect(page).to have_css('.alert-success')
Проверять селекоторы вообще никакого смысла нет. Надо проверять то, что пользователь видит на странице и что доказывает, что сценарий завершился успешно. в случае создания, юзер должен увидеть заголовок и тело вопроса на странице

2016-10-19 10:58 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +  scenario 'user can edit his question' do
Про редактрование вообще в задани пока ничего не было

2016-10-19 10:58 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +  scenario 'User can to create, edit and delete an answer' do
А чего сразу не view, create, update and delete? Разбивай сценарии и фичи на отельные логические части. Если одну часть уже протестировал, то не надо ее снова тестировать в другом сценарии.

2016-10-19 10:58 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +  scenario 'user dont have links to edit and delete other users records' do
Вот тебе ориентир: если видишь в названии теста или фичи "and", сразу разбивай на отдельные части

2016-10-20 10:40 UTC, tbilous commented on app/controllers/answers_controller.rb
> +  def index
У меня без него и редиректа проблема выскакивает
Юзер пишет ответ,
Юзер нажимает отправить, но ответ не проходит валидацию.
В строке браузера в этот момент http://localhost:3000/questions/4/answers
Если пользователь нажмёт обновить - ошибка отсутствия роута индекс. Этим костылём я выравниваю -роут есть, экшен перекидывает пользователя в вопрос.

Подскажи плз - как избежать этого.

2016-10-20 12:33 UTC, tbilous commented on app/controllers/answers_controller.rb
> +    @question = Answer.find(params[:id]).question
В load_answer @answer =  Answer.find(params[:id]) - мне показалось он не подходит, а дальше я не правильно  load_question написал, потому ставил костыли по дороге вместо того, что-бы посмотреть парамс, к примеру  у редактирования :(

По усложнению работы - специально. Больше сделаю -> больше опыта

2016-10-20 12:34 UTC, tbilous commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@question)
поправил

2016-10-20 12:34 UTC, tbilous commented on app/controllers/answers_controller.rb
> +    redirect_to question_path(@question)
Показалось "не dry" что одна и та же команда повторяется - сделал так. Но тут же провтыкал всюду переделать и получилось не то, что хотел.

Убрал метод

2016-10-20 12:35 UTC, tbilous commented on app/controllers/questions_controller.rb
> +    @question = current_user && current_user.questions.new
Да, так наглядней. Спасибо.

2016-10-20 12:35 UTC, tbilous commented on app/controllers/questions_controller.rb
> +    @answer = current_user && @question.answers.build
поправил

2016-10-20 12:35 UTC, tbilous commented on app/models/answer.rb
>    belongs_to :question
Не связывал. В проекте который делаю для себя ментор не рекомендовал  делать более одной ассоциации belongs_to..  Да и непонятно с логикой, если ассоциация пользователь-ответ с зависимостям - то не совсем логично,  если удален профайл - что-то происходит с ответом. Его лучше оставлять тут "навеки" а уходит он с базы только если удален ответ и т.д. и т.п. Если нет никаких каллбеков то зачем рельсу вообще привлекать. Потому и здесь так поступил
Если ты не согласен  - то переделаю.

2016-10-20 12:36 UTC, tbilous commented on app/models/user.rb
> +  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
Убрал

2016-10-20 12:37 UTC, tbilous commented on app/views/questions/index.html.slim
> +        = link_to 'Reg', new_user_registration_path
Думал их в меню прикрутить или боковой виджет. Смену войти,зарегистрироватся/выйти, профайл пользователя и т.д и т.п.. Просто не было времени. Сделаю как только часик появится это всё детальней  во вьюхе

2016-10-20 13:08 UTC, tbilous commented on spec/controllers/answers_controller_spec.rb
> +    @question_author_user = create :user
Там до трех пользователей в дальнейшем в тестах Вопрос - авт1, Ответ Авт-2, Вопрос и ответ авт-1, Вопопрос, ответ авт1  ответ авт2, активный -  пользователь авт3. Это ссылка к той проверке в контроллере где я допускал доступ к ответу и автора вопроса но пока не развивл ту тему.
В хелпере макрос от девайсовской вики с login_user. Но, показалось избыточным в хелпере писать несколько варианов сеансов там описывать, искать в тесте через сессию того который мне нужен и т.д. потому через sign_in user, sign_in other_user в сценариях овнер и не овнер, а там ещё и с фунционалом - @question_author_use,r автор вопроса имеет право проводить некоторые действия с ответом - подтянется.
let тут создает вопрос для тестирования ответов - используется в куче мест, я не понял как прибрать

2016-10-20 16:38 UTC, tbilous commented on app/controllers/questions_controller.rb
> +    redirect_to root_path, alert: 'NO RIGHTS!' if current_user != Question.find(params[:id]).user
поправил

2016-10-20 16:38 UTC, tbilous commented on spec/controllers/answers_controller_spec.rb
>        it 'save the new answer in a DB' do
Поправил

2016-10-20 16:38 UTC, tbilous commented on spec/controllers/answers_controller_spec.rb
> +      it 'delete from DB' do
Поправил

2016-10-20 16:39 UTC, tbilous commented on spec/controllers/answers_controller_spec.rb
> +    context 'user is not owner' do
переделал структуру теста контроллера ответа

2016-10-20 16:39 UTC, tbilous commented on spec/controllers/answers_controller_spec.rb
> +        let!(:answer) { create(:answer, question: question, user_id: @user.id) }
Переделал

2016-10-20 16:40 UTC, tbilous commented on spec/controllers/answers_controller_spec.rb
> +        context 'with valid attributes' do
написал

2016-10-20 16:40 UTC, tbilous commented on spec/controllers/answers_controller_spec.rb
> +      describe 'POST create' do
переделал тест контроллера ответа

2016-10-20 18:59 UTC, tbilous commented on spec/controllers/questions_controller_spec.rb
>  RSpec.describe QuestionsController, type: :controller do
Переделал

2016-10-20 19:32 UTC, tbilous commented on app/controllers/answers_controller.rb
> +    redirect_to root_path, alert: 'NO RIGHTS!' if current_user.id !=
Есть мысль дать и автору вопроса права на ответ: удаление, оценка автором, флаг - который автор вопроса назначает и т.д. и т.п. Но ещё не оформил в голове как это будет выглядеть. Потому оставил проверку такой, что-бы напоминала мне о себе.

Вынес в модель, Но опять же во вьюхе гораздо проще использовать вариант из хелпера, хотя-бы потому, что там он проверяет наличие current_user и меньше глубину во вьюшке делать, и ошибку на неавторизированном пользователе поймать - невозможно

Покажи плз как правильно сделать,  во вьюшке questin/show если закладываю под user_signed_in? то все равно ошибка.

2016-10-20 19:33 UTC, tbilous commented on app/views/questions/show.html.slim
> +  - if owner?(@question)
Прблема во вьюшке если неавторизированный пользователь. Покажи плз как сделать, Пробовал прятать под user_signed_in? - не помогает.

2016-10-20 19:35 UTC, tbilous commented on spec/features/question_pages_spec.rb
> +    expect(page).to_not have_link 'Delete answer'
Неавтризированный пользователь их не увидит. Так и относится.

2016-10-20 19:49 UTC, tbilous commented on spec/features/question_pages_spec.rb
> +    expect(page).to have_title 'Home page'
Вынес в отдельный файл который буду применять для тестрирования структуры страниц

2016-10-20 19:50 UTC, tbilous commented on spec/controllers/answers_controller_spec.rb
> +        let!(:answer) { create(:answer, question: question, user_id: @user.id) }
Ассоциации там нет - будет работать?

2016-10-20 20:27 UTC, tbilous commented on spec/features/question_pages_spec.rb
> +    expect(page).to have_css('.alert-success')
Как скажешь

2016-10-20 20:28 UTC, tbilous commented on spec/features/question_pages_spec.rb
> +  scenario 'user can edit his question' do
Добавил от скуки

2016-10-20 20:28 UTC, tbilous commented on spec/features/question_pages_spec.rb
> +  scenario 'User can to create, edit and delete an answer' do
разбил

2016-10-20 20:28 UTC, tbilous commented on spec/features/question_pages_spec.rb
> +  scenario 'user dont have links to edit and delete other users records' do
плюс

2016-10-20 20:28 UTC, tbilous commented on spec/features/question_pages_spec.rb
> +  scenario 'user see form on root page and can to create and to destroy the question' do
разбил

2016-10-20 20:29 UTC, tbilous commented on spec/features/question_pages_spec.rb
> +  User see form for question on root page
порезал

2016-10-20 20:32 UTC, tbilous commented on spec/features/question_pages_spec.rb
> +feature 'authorized have rights on create and edit question', %q{
переделал

2016-10-20 20:48 UTC, tbilous commented on app/helpers/owner_helper.rb
> +  def owner?(object)
Вынес
Хелпере пока использую во вьюшках, потому, что доп проверка позволяет не валится без добавления условий когда не авторизирован пользователь. С этим кстати торможу. Может затра свежим взглядом пойму может ты мне подскажешь как сделать, что-бы при условии на current_user все равно не валилаь страница

2016-10-20 20:49 UTC, tbilous commented on spec/features/question_pages_spec.rb
> +  scenario 'Root page have title' do
поправил

2016-10-21 09:39 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def index
Я бы просто забил на это, потому что это стандартное поведение рельс. Ну и при обновлении страницы, по идее, будет снова post-запрос и браузер спросит, хочешь ли ты повторно отправить форму.

2016-10-21 09:41 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @question = Answer.find(params[:id]).question
> По усложнению работы - специально. Больше сделаю -> больше опыта

Это успеешь еще наработать, не переживай. Так что не делай лишнего, тут бы успеть основную программу :-)

> В load_answer @answer = Answer.find(params[:id]) - мне показалось он не подходит, 
почему?

2016-10-21 09:43 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to root_path, alert: 'NO RIGHTS!' if current_user.id !=
Можно пойти "срединным путем": сделать метод в модели и еще и хелпер для видов, где вызывать и этот метод и проверку на юзера: `current_user && current_user.author_of?(...)`

2016-10-21 09:46 UTC, vkurennov commented on app/models/answer.rb
>    belongs_to :question
> В проекте который делаю для себя ментор не рекомендовал делать более одной ассоциации belongs_to.. 

Очень странная рекомендация. А как связи многие-ко-многим реализовывать? 

> Да и непонятно с логикой, если ассоциация пользователь-ответ с зависимостям - то не совсем логично, если удален профайл - что-то происходит с ответом. Его лучше оставлять тут "навеки" а уходит он с базы только если удален ответ и т.д. и т.п. Если нет никаких каллбеков то зачем рельсу вообще привлекать. Потому и здесь так поступил

Ну и как тогда проверять на автора?  Это раз, а насчет удаления при удалении юзера, никто не заставляет удалять ответы при этом. Пусть остаются, в чем проблема.

2016-10-21 09:48 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - if owner?(@question)
Вариант раз: `if current_user && current_user.author_of?`
Вариант два: `current_user.try(:author_of?, @question)`

2016-10-21 09:49 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        let!(:answer) { create(:answer, question: question, user_id: @user.id) }
Если ассоциации нет, то не будет

2016-10-21 09:51 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +    expect(page).to_not have_link 'Delete answer'
Мы тестируем **создание ответа**, а не удаление.  То есть наличие сссылки на удаление никак не относится к созданию ответа. Для незалогиненного юзера надо проверять, скажем, отсутсвие формы или еще что-то такое

2016-10-21 09:53 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +    expect(page).to have_css('.alert-success')
acceptance-тесты пишутся с точки зрения взаимодействия пользователя и системы. Это самое важное. Только так мы можем убедиться, что фича и сценарии работают как надо. Вдруг, у нас баг, alert-succes на странице добавляется, но не показывается, да и сам текст вопроса на страницу не выводится? Это нормальное поведение? Нет, но тест пройдет. Зачем он тогда нужен, этот тест?

2016-10-21 10:20 UTC, vkurennov requested changes
Исправь замечания

2016-10-21 10:20 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +                                                  (Answer.find(params[:id]).user_id ||
1. У тебя же уже точно загружен @answer, зачем ты его еще раз грузишь?
2. Ассоциациия @answer.question уже вернет тебе объект вопроса, не надо его снова грузить.
3. Используй метод author_of? о котором мы говорили.

2016-10-21 10:20 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question = current_user.questions.new if current_user
Тут не нужна проверка `if current_user`, т.к. дело до экшена не дойдет, если юзер не залогинен - девайс сделает редирект на страницу логина

2016-10-21 10:20 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @answer = @question.answers.build if current_user
Лишняя проверка на if current_user

2016-10-21 10:20 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :user_id)
useer_id не передается в параметрах формы, мы его берем через current_user

2016-10-21 10:20 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    redirect_to root_path, alert: 'NO RIGHTS!' if current_user.id != Question.find(params[:id]).user_id
И опять же @question уже загружен, и надо использовать метод `author_of?`

2016-10-21 10:20 UTC, vkurennov commented on app/helpers/owner_helper.rb
> +    current_user.try(:id) == object.try(:user_id)
Вынеси это в метод.

2016-10-21 10:20 UTC, vkurennov commented on app/models/answer.rb
>    belongs_to :question
И ведь фактически, ассоциация-то есть, раз поле user_id есть. То есть на уровне базы связь устанавливается, что доказывает факт, что невозможно писать модели с одной ассоциацией. Мне очень инетерсно обоснование рекомендации "использовать одну ассоциацию belongs_to"

2016-10-21 10:20 UTC, vkurennov commented on app/models/user.rb
> +  def owner?(object)
Вот твой метод, почему его не используешь в контроллерах, видах и хелперах?

2016-10-21 10:20 UTC, vkurennov commented on app/models/user.rb
> +  validates :name, length: 5..128
В моделях идут сначала ассоциации, потом валидации, потом скоупы и вызовы коллбеков и только потом идут методы

2016-10-21 10:20 UTC, vkurennov commented on app/views/questions/index.html.slim
> +        = link_to 'Reg', new_user_registration_path
А пока просто перенеси их в лейаут, потом красоту наведешь

2016-10-21 10:20 UTC, vkurennov commented on app/views/questions/show.html.slim
> +          - if user_signed_in?
Зачем двойной if? Объедени условия через &&

2016-10-21 10:20 UTC, vkurennov commented on app/views/questions/show.html.slim
> +            - if help_owner?(answer)
Странное название метода. Что оно означает? "помочь овнеру" или  "овнер помощи"? Если help от helper, то тоже плохая идея. Название метода должно отражать, что он делает, а не чем этот метод является.

2016-10-21 10:20 UTC, vkurennov commented on db/migrate/20161017203243_add_user_to_answers.rb
> +    add_column :answers, :user_id, :integer
А почему индекс не добавлен? Ведь по этому полю будет поиск, индекс значительно его ускорит

2016-10-21 10:20 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +          expect(Answer.where(id: answer.id, user_id: @other_user.id)).to_not be_empty
Получается, ты здесь тестируешь либо работу метода create из FactoryGirl, либо работу ассоциаций. Во-первых, не нужно делать ни то ни другое, во-вторых, ассоциации тестируются в моделях, а не в контроллере.

2016-10-21 10:20 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +          it 'add tot database' do
Надо проверить, что созданный вопрос связан с залогиненным юзером

2016-10-21 10:20 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        it 'save the new answer in a DB' do
Надо проверить, что **только что созданный ответ** связывается с залогиненным юзером. И то что написано выше никак это не проверяет, там идет проверка методов creaet из FactoryGirl, ассоциациий, чего угодно, но только не того, что запрос creaet в контроллер создает ответ и связывает его с залогиненным юзером.

2016-10-21 10:20 UTC, vkurennov commented on spec/features/answer_pages_spec.rb
> +feature 'you can write your title here', %q{
Одна фича - много сценариев, одна фича - один файл.

2016-10-21 10:20 UTC, vkurennov commented on spec/features/answer_pages_spec.rb
> +feature 'you can write your title here', %q{
Не по страницам разбивай, а по фичам

2016-10-21 10:20 UTC, vkurennov commented on spec/features/answer_pages_spec.rb
> +feature 'you can write your title here', %q{
Ну и супер название у фичи, ага :-)

2016-10-21 10:20 UTC, vkurennov commented on spec/features/answer_pages_spec.rb
> +  User see list of questions
Где в этой фиче сценарии, проверяющие то, что тут написано?

2016-10-21 10:20 UTC, vkurennov commented on spec/features/answer_pages_spec.rb
> +  scenario do
Что мы здесь проверяем? О чем сценарий?

2016-10-21 10:20 UTC, vkurennov commented on spec/features/answer_pages_spec.rb
> +  scenario 'User can to create an answer' do
После can to не пишется

2016-10-21 10:52 UTC, tbilous commented on spec/features/question_pages_spec.rb
> +    expect(page).to have_css('.alert-success')
Нет ли тут дублирования с тестом контроллера если мы роверяем добавленный ответ по его тексту или удаленный по таблице? А появления этих калбеков мы в контроллере не тестим, но есть ли они и в каком они виде - тоже надо проверять.

2016-10-21 10:57 UTC, tbilous commented on app/models/user.rb
> +  def owner?(object)
Потому, что  что if current_user.owner? мне валит стринцу если не активна сессия.

2016-10-21 10:59 UTC, tbilous commented on app/views/questions/show.html.slim
> +            - if help_owner?(answer)
Переименовал вчера в такой, что-бы заметней был.

2016-10-21 11:00 UTC, tbilous commented on spec/features/answer_pages_spec.rb
> +feature 'you can write your title here', %q{
;)

2016-10-21 11:03 UTC, tbilous commented on app/models/answer.rb
>    belongs_to :question
Ну не совсем - одну. Просто не увлекатся и меньше привлекать рельсу, что-бы не запутатся в калбеках. Думаю это скорее вопрос "религии", поэтому сегодня - переделаю.

2016-10-21 11:28 UTC, tbilous commented on app/views/questions/index.html.slim
> +        = link_to 'Reg', new_user_registration_path
Перенес

2016-10-21 11:46 UTC, tbilous commented on app/models/answer.rb
>    belongs_to :question
Переделал

2016-10-21 12:01 UTC, tbilous commented on app/controllers/questions_controller.rb
> +    @question = current_user.questions.new if current_user
убрал.

2016-10-21 12:01 UTC, tbilous commented on app/controllers/questions_controller.rb
> +    @answer = @question.answers.build if current_user
убрал

2016-10-21 12:02 UTC, tbilous commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :user_id)
убрал

2016-10-21 12:24 UTC, tbilous commented on app/helpers/owner_helper.rb
> +    current_user.try(:id) == object.try(:user_id)
заинклудил в контроллеры

2016-10-21 12:24 UTC, tbilous commented on app/models/user.rb
> +  validates :name, length: 5..128
поправил

2016-10-21 12:25 UTC, tbilous commented on spec/controllers/answers_controller_spec.rb
> +          expect(Answer.where(id: answer.id, user_id: @other_user.id)).to_not be_empty
Убрал, в тест модели добавил

2016-10-21 12:35 UTC, tbilous commented on spec/controllers/questions_controller_spec.rb
> +          it 'add tot database' do
Переделал

2016-10-21 12:36 UTC, tbilous commented on spec/controllers/answers_controller_spec.rb
> +        it 'save the new answer in a DB' do
Сделал по образцу проверки сохранения qeestion.answers

2016-10-21 12:57 UTC, tbilous commented on spec/features/answer_pages_spec.rb
> +  scenario do
Переделал

2016-10-21 12:57 UTC, tbilous commented on spec/features/answer_pages_spec.rb
> +  User see list of questions
переделал

2016-10-21 12:59 UTC, tbilous commented on spec/features/answer_pages_spec.rb
> +  scenario 'User can to create an answer' do
Упс

2016-10-21 13:01 UTC, tbilous commented on app/controllers/questions_controller.rb
> +    redirect_to root_path, alert: 'NO RIGHTS!' if current_user.id != Question.find(params[:id]).user_id
Передеал

2016-10-21 13:10 UTC, tbilous commented on app/views/questions/show.html.slim
> +          - if user_signed_in?
поправил

2016-10-21 14:18 UTC, vkurennov commented on app/models/answer.rb
>    belongs_to :question
Тогда проще вообще рельсу не использовать, если она не нравится :-) Но да, это холиварный вопрос немного.

2016-10-21 14:20 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +    expect(page).to have_css('.alert-success')
Нет, потому что мы разные аспекты проверяем. То, что юзер увидел что-то на странице, не гарантирует, что это попало в базу (может, мы через js добавили текст на страницу и все). А то, что что-то попало в базу, не гарантирует, что это увидел юзер.  В acceptance-тестах мы проверяем как ведет себя система с т.з. пользователя, а в юнит - как система ведет себя с т.з. внутреннего устройства.

О каких калбеках речь идет?

2016-10-21 14:21 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question = current_user.questions.new if current_user
А, сори, тут же нет обязательной авторизации, тогда оставь

2016-10-21 14:23 UTC, vkurennov commented on app/models/user.rb
> +  def owner?(object)
Ну так сделай составное условие: `if current_user && current_user.owner?`
И что значит "неактивна сессия"? В смысле юзер не залогинен?

2016-10-21 14:36 UTC, vkurennov requested changes
Разбей уже acceptance-тесты на нормальные файлы и фичи. **Каждая история пользователя - это отдельная фича".

2016-10-21 14:36 UTC, vkurennov commented on app/helpers/owner_helper.rb
> +module OwnerHelper
Да удали ты нафиг этот модуль, не нужен он тебе. Юзай метод owner из модели. Ну или хотя бы перепиши этот хелпер так, чтобы использовался метод из модели

2016-10-21 14:36 UTC, vkurennov commented on db/migrate/20161021110002_add_index_to_answers.rb
> +    add_index :answers, :user_id
И foreign_key тоже не помешает

2016-10-21 14:36 UTC, vkurennov commented on spec/features/answer_pages_spec.rb
> +    question = Question.create!(title: question_params[:title], body: question_params[:body])
А зачем брать question_params, если можно выполнить creaete(:question) и объект будет создан из фабрики с этими параметрами?

2016-10-21 14:36 UTC, vkurennov commented on spec/features/answer_pages_spec.rb
> +    expect(page).to have_css('.alert-success')
И тут надо проверить, что на странице появился ответ

2016-10-21 14:36 UTC, vkurennov commented on spec/features/answer_pages_spec.rb
> +    expect(page).to have_css('.alert-success')
И надо проверить, что на странице нет больше ответа. И еще нужен сценарий, когда не-автор не видит ссылки на удаление

2016-10-21 14:36 UTC, vkurennov commented on spec/features/answer_pages_spec.rb
> +  scenario 'User can to edit  an answer' do
Создание, просмотр, удаление, редактирование - это разные фичи, они должны быть в разных файлах и включают они разные сценарии.

2016-10-21 14:36 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +    expect(page).to have_css('.alert-success')
И надо проверить , что на странице появились загловок и текст вопроса

2016-10-21 14:36 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +    expect(page).to have_title 'Home page'
Надо не заголовок страницы проверять, а то, что на странице больше нет этого вопроса.

2016-10-21 14:36 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +    expect(page).to have_title 'Home page'
Ну и сценарий для не-автора

2016-10-21 15:31 UTC, tbilous commented on app/helpers/owner_helper.rb
> +module OwnerHelper
Переписал. Но тут я почему так. Если в контроллере описывать - надо его в хелпер метод, что-бы во вьюв был. Если в хелпере - то инклуд. Что в лоб, что по лбу. Да и ещё в обеих контроллерах прописать

2016-10-21 15:35 UTC, tbilous commented on db/migrate/20161021110002_add_index_to_answers.rb
> +    add_index :answers, :user_id
:8ball: 
Добавил

2016-10-21 15:39 UTC, tbilous commented on spec/features/answer_pages_spec.rb
> +    question = Question.create!(title: question_params[:title], body: question_params[:body])
Я его в click_on(question_params[:title], match: :first) использую, потому так и сделал, что-бы опять же не тянуть  с вопроса.

2016-10-21 15:48 UTC, tbilous commented on spec/features/answer_pages_spec.rb
> +    expect(page).to have_css('.alert-success')
Добавил

2016-10-21 15:49 UTC, tbilous commented on spec/features/answer_pages_spec.rb
> +  scenario 'User can to edit  an answer' do
я, видимо туплю. Тут сценарий только на редактирование..

2016-10-21 15:53 UTC, tbilous commented on spec/features/answer_pages_spec.rb
> +    expect(page).to have_css('.alert-success')
Добавил

2016-10-21 20:40 UTC, vkurennov requested changes

2016-10-21 20:40 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question = current_user.questions.new if current_user
Кстати, для new связи не важны, поэтому можно было просто Question.new сделать и тогда current_user не понадобится

2016-10-21 20:40 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def owner_of?(object)
Ну сколько ты будешь этот несчатсный метод гонять туда сюда? Убери ты его вообще, у тебя есть метод  `User#owner?`  вот его и используй

2016-10-21 20:40 UTC, vkurennov commented on app/helpers/owner_helper.rb
> +module OwnerHelper
> Что в лоб, что по лбу.

Вот именно. Поэтому, надо его в модель перенести (точнее, там он уже есть) и вызывать у модели

2016-10-21 20:40 UTC, vkurennov commented on app/models/user.rb
> +  def owner?(object)
Чем тебя не устраивает этот метод? Тем, что если юзер не залогинен, то его не вызывать? Сделай двойную проверку или вызывай метод через try

2016-10-21 20:40 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +feature 'User is not authorized', %q{
Да не фича это. Фича - "Пользователь может удалить ответ", "Пользователь может создать ответ". Т.е. истори  - это и есть фичи. А варианты с авторизованным/неавторизованным юзером - это контексты и разные сценарии в рамках данных фич. То есть у тебя с ног на голову все поставлено. Посмотри еще раз 1-й скринкаст про истории и 5-й про acceptance-тесты. Ты где-то там видишь, что мы в описании фичи прописываем истории пользователя?

2016-10-21 20:40 UTC, vkurennov commented on spec/features/question_pages_spec.rb
> +feature 'user is authorized', %q{
Сколько раз надо написать, что каждая фича должна быть в отдельном файле, и что фича - это история пользователя? У тебя есть истории в описании. Вот теперь возьми и каждую из них покрой тестами (сценариями) и реализуй их все в отдельных файлах.

2016-10-23 09:44 UTC, vkurennov approved these changes
Принято

2016-10-23 10:33 UTC, merged